name = "Fortran-tooling"
version = "0.1.0"
license = "MIT"
author = "Connor Aird, Mashy Green, Duncan Leggat, Ilektra Christidi, Tuomas Koskela"
maintainer = "c.aird@ucl.ac.uk"
copyright = "Copyright 2025, UCL ARC"

[fortran]
source-form = "free"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.5.0"
veggies.git = "https://gitlab.com/everythingfunctional/veggies"
veggies.tag = "main"

[[executable]]
name = "poisson"
source-dir = "src/poisson"
main = "main.f90"

[[executable]]
name = "mesh_generator"
source-dir = "src/mesh_generator"
main = "main.f90"

[[test]]
name = "test-drive-tests"
source-dir = "testing/test-drive"
main = "main.f90"

[[test]]
name = "veggies-tests"
source-dir = "testing/veggies"
main = "main.f90"

[extra.ford]
project = "Fortran-tooling"
doc_license = "mit"
favicon = "documentation/ford/media/fortran-tooling.png"
license = "mit"
project_github = "https://github.com/UCL-ARC/fortran-tooling"
author = "UCL, ARC"
github = "https://github.com/UCL-ARC"
exclude_dir = "debugging"
page_dir = "."
src_dir = ["src", "testing"]
extensions = ["f90", "pf"]
fixed_length_limit = false
predocmark = ">"
predocmark_alt = "<"
preprocess = false
css = "documentation/ford/css/site-wide.css"
display = ["public", "protected", "private"]
print_creation_date =  true
creation_date = "%Y-%m-%d %H:%M (UTC%z)"
proc_internals =  true
search =  true
sort = "permission"
graph =  false
graph_maxnodes = 1000
graph_maxdepth = 1
md_extensions = "markdown.extensions.toc"
hide_undoc =  true
