name = "Fortran-tooling"
version = "0.1.0"
license = "MIT"
author = "Connor Aird, Mashy Green, Duncan Leggat, Ilektra Christidi, Tuomas Koskela"
maintainer = "c.aird@ucl.ac.uk"
copyright = "Copyright 2025, UCL ARC"

[fortran]
source-form = "free"

[[executable]]
name = "poisson"
source-dir = "src/poisson"
main = "main.f90"

[[executable]]
name = "mesh_generator"
source-dir = "src/mesh_generator"
main = "main.f90"
