# Based on https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
---
name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Install pre-commit
        shell: bash
        run: python -m pip install pre-commit

      - name: Run pre-commit
        shell: bash
        run: pre-commit run --all-files --color always --verbose
